# Generated by Django 4.1.4 on 2023-08-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aayesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='do_you_agree_that_converion_is_a_solution_for_untouchability',
            new_name='do_you_agree_that_conversion_is_a_solution_for_untouchability',
        ),
    ]
