# Generated by Django 4.1.4 on 2023-08-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayesapp', '0010_member_password_alter_member_approved_by_dc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='password',
            field=models.CharField(default='admin', max_length=150),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='admin', max_length=150),
        ),
    ]
