# Generated by Django 4.1.4 on 2023-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayesapp', '0012_rename_do_you_think_untouchability_related_to_religion_application_hours_can_dedicate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='marital_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
