# Generated by Django 4.1.4 on 2023-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayesapp', '0013_alter_application_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='monthly_income',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
