# Generated by Django 4.1.4 on 2023-08-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayesapp', '0018_alter_application_additional_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='hours_can_you_dedicate',
        ),
        migrations.AddField(
            model_name='member',
            name='hours_can_dedicate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='additional_skills',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='affiliated_to_any_political_party',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='affiliated_with_any_ngo_or_trust',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='approved_by_dc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='approved_by_sc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='approved_by_zc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='believe_in_god',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='believe_in_rituals',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='call_brahmins_for_rituals',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='cause_for_untouchability',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='do_you_agree_that_conversion_is_a_solution_for_untouchability',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='father_or_spouse_monthly_income',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='father_or_spouse_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='father_or_spouse_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='hobby',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='how_many_assistant_district_coordinators_you_can_gather',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='invoved_in_any_social_activities',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_untouchability_prevalent_nowadays',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='main_problem_of_dalits',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='money_can_you_donate_per_month',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='monthly_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='number_of_children',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='own_vehicle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='read_ambedkar_books',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='religion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='social_media_account',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='solution_for_untouchability_your_pov',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='solution_given_by_dr_ambedkar_for_untouchability',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='untouchability_related_to_religion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='willing_to_attend_residential_training_programs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='willing_to_visit_adw_hostels',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='willing_to_volunteer_for_free',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='worship_of_heirlooms',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
