# Generated by Django 4.1.4 on 2023-08-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayesapp', '0019_remove_member_hours_can_you_dedicate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending Approval of District Coordinator', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='Pending Approval of District Coordinator', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.CharField(choices=[('DC', 'District Coordinator'), ('ADC', 'Associate District Coordinator'), ('ZC', 'Zonal District Coordinator'), ('SC', 'State Coordinator'), ('DADW', 'District of Adi Dravida Welfare'), ('WARDAN', 'Wardan'), ('DONOR', 'Donor'), ('RP', 'Resource Person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('DC', 'District Coordinator'), ('ADC', 'Associate District Coordinator'), ('ZC', 'Zonal District Coordinator'), ('SC', 'State Coordinator'), ('DADW', 'District of Adi Dravida Welfare'), ('WARDAN', 'Wardan'), ('DONOR', 'Donor'), ('RP', 'Resource Person')], max_length=50),
        ),
    ]
